version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: NuGet
  api_key:
    secure: F/AkZSLJHX8tWvRwFal7sgeOrkS9g0v2RtxxZd/Aqi6mRc9xq7xBEM9EOdlV86ni
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
- provider: GitHub
  tag: UltraMapper v$(appveyor_build_version)
  release: UltraMapper v$(appveyor_build_version)
  auth_token:
    secure: LKiVjOB59Iiuz3a9YpRFgucyLD4dXWGRIQLpicJr2dYmQvrsgDGj3FhLgjmbUNi1oc0TtnydB3PdP3iYnxjRtBljjVrjI+mHHTg5oUQxjRQ=
  artifact: /.*\.nupkg/
