version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: oy2j6myyrev2ndqd4mdq2o5vhtgid2huznvidzs4hbejey
  skip_symbols: true
- provider: GitHub
  tag: UltraMapper v$(appveyor_build_version)
  release: UltraMapper v$(appveyor_build_version)
  auth_token:
    secure: mCdfTt2M2W/zNeRMTEuINe7mLJKW3MjB69S3VZS5e1VW0UOPLr1MvAY1Ep6feU3b
  artifact: /.*\.nupkg/
